compile:
  image: httpd:latest
  script:
    - docker-compose down --remove-orphans
    - docker-compose up --force-recreate --build
    - $(pwd)/entrypoint.sh
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
  tags:
    - http-docker
  only: # on what branch we'd like to run this job
    refs:
      - master