compile:
  image: httpd:latest
  script:
    # - docker-compose down --remove-orphans
    - ip a | grep inet
    - echo $(pwd)
    - $(pwd)/entrypoint.sh
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
  tags:
    - http-docker
  only: # on what branch we'd like to run this job
    refs:
      - master