compile:
  image: httpd:latest
  before_script:
    - docker rmi -f httpd:latest || true  # Remove the existing image (ignore errors)
  script:
    - $(pwd)/entrypoint.sh
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
  tags:
    - http-docker
  only: # on what branch we'd like to run this job
    refs:
      - master