######################################################
# Title: Compile mod_auth_openidc module
# Author: AMVARA CONSULTING S.L.
# Date: 2021-12-28
######################################################
# Usage: docker-compose up 
######################################################
# CHANGELOG:
# 2021-12-28  Arslan  Created this file. 
######################################################

version: "3"
services:
  apache:
    image: "httpd:latest"
    container_name: oidc_compiler
    volumes:
      - "./entrypoint.sh:/code/entrypoint.sh:ro" # entrypoint that will build the module
      - "./dist:/code/dist:rw" # folder where the module will be placed after compile
    working_dir: /code
    command: bash /code/entrypoint.sh